import {expect,test} from '@playwright/test';

test('public case study never requests private telemetry',async({page})=>{const calls:string[]=[];page.on('request',r=>{if(r.url().includes('/api/'))calls.push(r.url())});await page.goto('/');await expect(page.getByRole('heading',{name:/Vulnerability data/i})).toBeVisible();await expect(page.getByText(/Historical sanitized data/i)).toBeVisible();expect(calls).toEqual([])});

test('operator can sign in and follow an approved scan',async({page})=>{
  const request={id:'11111111-1111-1111-1111-111111111111',targetId:'22222222-2222-2222-2222-222222222222',targetName:'alpine-demo',requestedBy:'operator',agentId:'agent-1',status:'RUNNING',recoveryAttempts:0,requestedAt:'2026-08-29T10:00:00Z',claimedAt:'2026-08-29T10:00:01Z',startedAt:'2026-08-29T10:00:02Z'};
  await page.route('**/api/ui/v1/**',async route=>{const url=new URL(route.request().url());const path=url.pathname;if(path.endsWith('/auth/csrf'))return route.fulfill({json:{token:'test-csrf'}});if(path.endsWith('/auth/login')||path.endsWith('/auth/me'))return route.fulfill({json:{id:'u1',username:'operator',role:'OPERATOR',passwordChangeRequired:false}});if(path.endsWith('/targets'))return route.fulfill({json:[{id:request.targetId,name:'alpine-demo'}]});if(path.endsWith('/scan-requests')&&route.request().method()==='POST')return route.fulfill({json:request});if(path.endsWith('/scan-requests'))return route.fulfill({json:{content:[request],number:0,totalPages:1,totalElements:1}});if(path.endsWith(request.id))return route.fulfill({json:request});return route.fulfill({status:404,json:{message:'not mocked'}})});
  await page.goto('/login');await page.getByLabel('Username').fill('operator');await page.getByLabel('Password').fill('TemporaryPassword1A');await page.getByRole('button',{name:'Sign in securely'}).click();await page.goto('/app/scans');await page.getByLabel('Launch approved scan').selectOption(request.targetId);await expect(page.getByRole('heading',{name:'alpine-demo'})).toBeVisible();await expect(page.getByText('Execution timeline')).toBeVisible();await expect(page.getByRole('link',{name:'Users'})).toHaveCount(0);
});
