export type DemoStage = {
  state: string;
  label: string;
  eventId: string;
  timestamp: string;
  latency: string;
  detail: string;
};
export type PublicFinding = {
  vulnerabilityId: string;
  packageName: string;
  installedVersion: string;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN";
  title: string;
  knownExploited: boolean;
  riskScore: number;
};

// Historical production evidence captured from the read-only AWS result API.
// The public page never calls the private API or DynamoDB directly.
export const recordedScan = {
  evidenceId: "debian-11-slim-2026-08-02",
  target: "debian:11-slim",
  reportFile: "report.json",
  reportSize: "712.9 KB",
  reportHash: "sha256:638f2008…cb51b",
  contentHash: "638f2008ae9ecbcb15d36c20c31e344608c369918af6af8e782325e9d86cb51b",
  scanner: "Trivy",
  duration: "29.3 s",
  scanId: "d77aa2bc-e032-497f-a4ef-defd6ddbff21",
  eventId: "51c9d394-9101-497c-9105-220af588b7a8",
  correlationId: "b7d92ca9-8499-43dd-8b1c-6da5c83d9412",
  capturedAt: "2 Aug 2026, 12:20 UTC",
  totalFindings: 190,
  summary: { CRITICAL: 6, HIGH: 19, MEDIUM: 60, LOW: 97, UNKNOWN: 8 },
  stages: [
    {
      state: "RECEIVED",
      label: "Report accepted and stored",
      eventId: "51c9d394…b7a8",
      timestamp: "12:19:49.829",
      latency: "0 ms",
      detail: "The API authenticated the upload, stored the Trivy JSON in the private S3 bucket and committed the scan with its content hash.",
    },
    {
      state: "OUTBOXED",
      label: "Publication intent committed",
      eventId: "51c9d394…b7a8",
      timestamp: "12:19:49.829",
      latency: "same transaction",
      detail: "PostgreSQL recorded the event before publication, so a process failure could not silently lose the hand-off.",
    },
    {
      state: "PUBLISHED",
      label: "Event delivered to SQS",
      eventId: "51c9d394…b7a8",
      timestamp: "12:19:51.383",
      latency: "1.6 s",
      detail: "The outbox publisher sent the persisted event to the bounded ingestion queue.",
    },
    {
      state: "COMPLETED",
      label: "Result persisted in DynamoDB",
      eventId: "51c9d394…b7a8",
      timestamp: "12:20:19.117",
      latency: "27.7 s",
      detail: "Lambda parsed the S3 report idempotently and stored the summary plus 190 findings in DynamoDB.",
    },
  ] satisfies DemoStage[],
  findings: [
    {
      vulnerabilityId: "CVE-2011-3374",
      packageName: "apt",
      installedVersion: "2.2.4",
      severity: "LOW",
      title: "apt-key does not correctly validate GPG keys with the master keyring",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2022-3715",
      packageName: "bash",
      installedVersion: "5.1-2+deb11u1",
      severity: "HIGH",
      title: "Heap buffer overflow in valid_parameter_transform",
      knownExploited: false,
      riskScore: 70,
    },
    {
      vulnerabilityId: "TEMP-0841856-B18BAF",
      packageName: "bash",
      installedVersion: "5.1-2+deb11u1",
      severity: "LOW",
      title: "Privilege escalation possible to another non-root user",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2026-53615",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "HIGH",
      title: "Integer overflow or wraparound in libblkid DOS partition parsing",
      knownExploited: false,
      riskScore: 70,
    },
    {
      vulnerabilityId: "CVE-2026-13595",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "MEDIUM",
      title: "Heap use-after-free during nested partition probing",
      knownExploited: false,
      riskScore: 40,
    },
    {
      vulnerabilityId: "CVE-2026-27456",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "MEDIUM",
      title: "TOCTOU in mount when setting up loop devices",
      knownExploited: false,
      riskScore: 40,
    },
    {
      vulnerabilityId: "CVE-2026-3184",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "MEDIUM",
      title: "Access-control bypass caused by improper hostname canonicalization",
      knownExploited: false,
      riskScore: 40,
    },
    {
      vulnerabilityId: "CVE-2022-0563",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "LOW",
      title: "Partial disclosure of arbitrary files through chfn and chsh",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2025-14104",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "LOW",
      title: "Heap buffer over-read while processing long usernames",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2026-53613",
      packageName: "bsdutils",
      installedVersion: "1:2.36.1-8+deb11u2",
      severity: "UNKNOWN",
      title: "Local privilege escalation through a mount TOCTOU condition",
      knownExploited: false,
      riskScore: 0,
    },
    {
      vulnerabilityId: "CVE-2016-2781",
      packageName: "coreutils",
      installedVersion: "8.32-4+b1",
      severity: "LOW",
      title: "Non-privileged session can escape to the parent session in chroot",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2017-18018",
      packageName: "coreutils",
      installedVersion: "8.32-4+b1",
      severity: "LOW",
      title: "Race-condition vulnerability in chown and chgrp",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2025-5278",
      packageName: "coreutils",
      installedVersion: "8.32-4+b1",
      severity: "LOW",
      title: "Heap buffer under-read in sort through key specification",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2026-56391",
      packageName: "coreutils",
      installedVersion: "8.32-4+b1",
      severity: "LOW",
      title: "Out-of-bounds read in uniq with multibyte input",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2026-56392",
      packageName: "coreutils",
      installedVersion: "8.32-4+b1",
      severity: "LOW",
      title: "Denial of service in unexpand through crafted tab stops",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2026-53910",
      packageName: "diffutils",
      installedVersion: "1:3.7-5",
      severity: "LOW",
      title: "Heap-based buffer issue in diff3",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2023-4039",
      packageName: "gcc-10-base",
      installedVersion: "10.2.1-6",
      severity: "LOW",
      title: "Stack protector fails to guard dynamic allocations on ARM64",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2023-4039",
      packageName: "gcc-9-base",
      installedVersion: "9.3.0-22",
      severity: "LOW",
      title: "Stack protector fails to guard dynamic allocations on ARM64",
      knownExploited: false,
      riskScore: 20,
    },
    {
      vulnerabilityId: "CVE-2025-30258",
      packageName: "gpgv",
      installedVersion: "2.2.27-2+deb11u3",
      severity: "MEDIUM",
      title: "Verification denial of service through a malicious subkey",
      knownExploited: false,
      riskScore: 40,
    },
    {
      vulnerabilityId: "CVE-2025-68972",
      packageName: "gpgv",
      installedVersion: "2.2.27-2+deb11u3",
      severity: "MEDIUM",
      title: "Signature bypass through a form-feed character in signed messages",
      knownExploited: false,
      riskScore: 40,
    },
  ] satisfies PublicFinding[],
} as const;
